Add mongodb writer.
NASA-NAVO/servicemon pull request #36
Opened 2020-11-08 01:48 UTC by JohnGood

The mongo_writer.py file is the only change.

2020-12-07 18:22 UTC, tomdonaldson requested changes
I jumped to conclusions last week when I thought Travis was responsible for the CI errors in your pull request.  It looks like we still have a few credits left where they're run CI for servicemon.  I'll need to switch over to github actions soon though.

Anyway, the two issues are definitely fixable:

1)  A broken regression test:  
At servicemon/tests/test_plugin_support.py:39 the assertion fails because the count there needs to be incremented to account for your plugin which is automatically discovered.

2)  There are a few ticky tack violations of the codestyle check.

Assuming you've set up your dev environment with `pip install -e .`, and installed `tox`, you can run the regression tests locally with `tox -e test` or `pytest`, and can run the codestyle checks locally with `tox -e codestyle`.

2020-12-07 18:22 UTC, tomdonaldson commented on servicemon/builtin_plugins/mongo_writer.py
> +        print(jsonStr)
Is this needed?  It will either collect in the output file, ir get thrown away when the output file is disabled by default.

2020-12-07 18:22 UTC, tomdonaldson commented on servicemon/builtin_plugins/mongo_writer.py
> +            file.close()
This `close()` seems unnecessary since it's part of the `with` block.

2020-12-09 00:03 UTC, JohnGood commented
Both changes have been made.

2020-12-09 13:08 UTC, tomdonaldson commented
> I jumped to conclusions last week when I thought Travis was responsible for the CI errors in your pull request. It looks like we still have a few credits left where they're run CI for servicemon. I'll need to switch over to github actions soon though.
> 
> Anyway, the two issues are definitely fixable:
> 
> 1. A broken regression test:
>    At servicemon/tests/test_plugin_support.py:39 the assertion fails because the count there needs to be incremented to account for your plugin which is automatically discovered.
> 2. There are a few ticky tack violations of the codestyle check.
> 
> Assuming you've set up your dev environment with `pip install -e .`, and installed `tox`, you can run the regression tests locally with `tox -e test` or `pytest`, and can run the codestyle checks locally with `tox -e codestyle`.

@JohnGood  I'm still seeing these CI issues.  Not sure if they were intended to be addressed yet.

2020-12-09 22:37 UTC, closed without merging